name: 'dd-action'
description: 'Uploading security report to DefectDojo '
author: 'yamaks2306'

inputs:
  mode:
    description: 'init or upload_report'
    required: true
  url:
    description: 'DefectDojo URL'
    required: true
  token:
    description: "DefectDojo token"
    required: true
  product_type:
    description: "DefectDojo product type (for examole, project name)"
  product:
    description: "DefectDojo product, default - repository name"
    default: ${{ github.repository }}
  product_description:
    description: "DefectDojo product description, default - github repo url"
    default: ${{ github.repositoryUrl }}
  engagement_type: 
    description: "DefectDojo Engagement type"
    default: "CI/CD"
  scan_type: 
    description: "Scan type format, default - SARIF"
    default: "SARIF"
  engagement_id:
    description: "Engagement id from init mode"
  test_title:
    description: "Type of test, for example - image, config or code"
  active:
    description: "Finding state, default - true"
    default: "True"
  verified:
    description: "Finding acception, default - false"
    default: "False"
  close_old_findings:
    description: "Close or not old findings, default - true"
    default: "True"
  deduplication_on_engagement:
    description: "Default True"
    default: "True"
  file:
    description: "File to upload"

outputs:
  engagement_id:
    description: "DefectDojo Engagement id"
    value: ${{ steps.dd-action.outputs.ENGAGEMENT_ID }}

  product_id: 
    description: 'DefectDojo Product id' 
    value: ${{ steps.dd-action.outputs.PRODUCT_ID }}

  product_type_id: 
    description: 'DefectDojo Product type id'
    value: ${{ steps.dd-action.outputs.PRODUCT_TYPE_ID }}

runs:
  using: 'composite'
  steps:

    - shell: bash
      id: dd-action
      run: python3 ${{ github.action_path }}/main.py
      env:
        MODE: ${{ inputs.mode }}
        DD_URL: ${{ inputs.url }}
        DD_TOKEN: ${{ inputs.token }}
        GITHUB_RUN_ID: ${{ github.run_id}}
        GITHUB_SHA: ${{ github.sha }}
        PRODUCT_TYPE: ${{ inputs.product_type }}
        PRODUCT: ${{ inputs.product }}
        PRODUCT_DESCRIPTION: ${{inputs.product_description }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REPOSITORY: 'https://github.com/${{ github.repository }}'
        ENGAGEMENT_TYPE: ${{ inputs.engagement_type }}
        SCAN_TYPE: ${{ inputs.scan_type }}
        ENGAGEMENT_ID: ${{ inputs.engagement_id}}
        TEST_TITLE: ${{ inputs.test_title }}
        ACTIVE: ${{ inputs.active }}
        VERIFIED: ${{ inputs.verified }}
        CLOSE_OLD_FINDINGS: ${{ inputs.close_old_findings }}
        DEDUPLICATION_ON_ENGAGEMENT: ${{ inputs.deduplication_on_engagement }}
        FILE: ${{ inputs.file }}

branding:
  icon: 'send'
  color: 'blue'